platform :ios, '9.0'

target 'ToptoTop' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'Masonry'
  pod 'CocoaAsyncSocket', '~> 7.6.1'
  pod 'MBProgressHUD', '~> 1.0.0'
  pod 'SGQRCode', '~> 2.2.0'
  pod 'JSONModel', '~> 1.7.0'
  pod 'SVProgressHUD', '~> 2.2.5'
end

